"use strict";

exports.__esModule = true;
exports.AUTH_FAILURE = exports.AUTH_SUCCESS = exports.AUTH_REQUEST = exports.LOGOUT = exports.UPDATE_JWT = exports.HOT_MODULE_REPLACEMENT = exports.DROP_READMODEL_STATE = exports.LOAD_READMODEL_STATE_FAILURE = exports.LOAD_READMODEL_STATE_SUCCESS = exports.LOAD_READMODEL_STATE_REQUEST = exports.DISCONNECT_READMODEL = exports.CONNECT_READMODEL = exports.DROP_VIEWMODEL_STATE = exports.LOAD_VIEWMODEL_STATE_FAILURE = exports.LOAD_VIEWMODEL_STATE_SUCCESS = exports.LOAD_VIEWMODEL_STATE_REQUEST = exports.DISCONNECT_VIEWMODEL = exports.CONNECT_VIEWMODEL = exports.UNSUBSCRIBE_TOPIC_FAILURE = exports.UNSUBSCRIBE_TOPIC_SUCCESS = exports.UNSUBSCRIBE_TOPIC_REQUEST = exports.SUBSCRIBE_TOPIC_FAILURE = exports.SUBSCRIBE_TOPIC_SUCCESS = exports.SUBSCRIBE_TOPIC_REQUEST = exports.DISPATCH_TOPIC_MESSAGE = exports.SEND_COMMAND_FAILURE = exports.SEND_COMMAND_SUCCESS = exports.SEND_COMMAND_REQUEST = void 0;
var SEND_COMMAND_REQUEST = '@@resolve/SEND_COMMAND_REQUEST';
exports.SEND_COMMAND_REQUEST = SEND_COMMAND_REQUEST;
var SEND_COMMAND_SUCCESS = '@@resolve/SEND_COMMAND_SUCCESS';
exports.SEND_COMMAND_SUCCESS = SEND_COMMAND_SUCCESS;
var SEND_COMMAND_FAILURE = '@@resolve/SEND_COMMAND_FAILURE'; //

exports.SEND_COMMAND_FAILURE = SEND_COMMAND_FAILURE;
var DISPATCH_TOPIC_MESSAGE = '@@resolve/DISPATCH_TOPIC_MESSAGE'; //

exports.DISPATCH_TOPIC_MESSAGE = DISPATCH_TOPIC_MESSAGE;
var SUBSCRIBE_TOPIC_REQUEST = '@@resolve/SUBSCRIBE_TOPIC_REQUEST';
exports.SUBSCRIBE_TOPIC_REQUEST = SUBSCRIBE_TOPIC_REQUEST;
var SUBSCRIBE_TOPIC_SUCCESS = '@@resolve/SUBSCRIBE_TOPIC_SUCCESS';
exports.SUBSCRIBE_TOPIC_SUCCESS = SUBSCRIBE_TOPIC_SUCCESS;
var SUBSCRIBE_TOPIC_FAILURE = '@@resolve/SUBSCRIBE_TOPIC_FAILURE';
exports.SUBSCRIBE_TOPIC_FAILURE = SUBSCRIBE_TOPIC_FAILURE;
var UNSUBSCRIBE_TOPIC_REQUEST = '@@resolve/UNSUBSCRIBE_TOPIC_REQUEST';
exports.UNSUBSCRIBE_TOPIC_REQUEST = UNSUBSCRIBE_TOPIC_REQUEST;
var UNSUBSCRIBE_TOPIC_SUCCESS = '@@resolve/UNSUBSCRIBE_TOPIC_SUCCESS';
exports.UNSUBSCRIBE_TOPIC_SUCCESS = UNSUBSCRIBE_TOPIC_SUCCESS;
var UNSUBSCRIBE_TOPIC_FAILURE = '@@resolve/UNSUBSCRIBE_TOPIC_FAILURE'; //

exports.UNSUBSCRIBE_TOPIC_FAILURE = UNSUBSCRIBE_TOPIC_FAILURE;
var CONNECT_VIEWMODEL = '@@resolve/CONNECT_VIEWMODEL';
exports.CONNECT_VIEWMODEL = CONNECT_VIEWMODEL;
var DISCONNECT_VIEWMODEL = '@@resolve/DISCONNECT_VIEWMODEL';
exports.DISCONNECT_VIEWMODEL = DISCONNECT_VIEWMODEL;
var LOAD_VIEWMODEL_STATE_REQUEST = '@@resolve/LOAD_VIEWMODEL_STATE_REQUEST';
exports.LOAD_VIEWMODEL_STATE_REQUEST = LOAD_VIEWMODEL_STATE_REQUEST;
var LOAD_VIEWMODEL_STATE_SUCCESS = '@@resolve/LOAD_VIEWMODEL_STATE_SUCCESS';
exports.LOAD_VIEWMODEL_STATE_SUCCESS = LOAD_VIEWMODEL_STATE_SUCCESS;
var LOAD_VIEWMODEL_STATE_FAILURE = '@@resolve/LOAD_VIEWMODEL_STATE_FAILURE';
exports.LOAD_VIEWMODEL_STATE_FAILURE = LOAD_VIEWMODEL_STATE_FAILURE;
var DROP_VIEWMODEL_STATE = '@@resolve/DROP_VIEWMODEL_STATE'; //

exports.DROP_VIEWMODEL_STATE = DROP_VIEWMODEL_STATE;
var CONNECT_READMODEL = '@@resolve/CONNECT_READMODEL';
exports.CONNECT_READMODEL = CONNECT_READMODEL;
var DISCONNECT_READMODEL = '@@resolve/DISCONNECT_READMODEL';
exports.DISCONNECT_READMODEL = DISCONNECT_READMODEL;
var LOAD_READMODEL_STATE_REQUEST = '@@resolve/LOAD_READMODEL_STATE_REQUEST';
exports.LOAD_READMODEL_STATE_REQUEST = LOAD_READMODEL_STATE_REQUEST;
var LOAD_READMODEL_STATE_SUCCESS = '@@resolve/LOAD_READMODEL_STATE_SUCCESS';
exports.LOAD_READMODEL_STATE_SUCCESS = LOAD_READMODEL_STATE_SUCCESS;
var LOAD_READMODEL_STATE_FAILURE = '@@resolve/LOAD_READMODEL_STATE_FAILURE';
exports.LOAD_READMODEL_STATE_FAILURE = LOAD_READMODEL_STATE_FAILURE;
var DROP_READMODEL_STATE = '@@resolve/DROP_READMODEL_STATE'; //

exports.DROP_READMODEL_STATE = DROP_READMODEL_STATE;
var HOT_MODULE_REPLACEMENT = '@@resolve/HOT_MODULE_REPLACEMENT'; //

exports.HOT_MODULE_REPLACEMENT = HOT_MODULE_REPLACEMENT;
var UPDATE_JWT = '@@resolve/UPDATE_JWT';
exports.UPDATE_JWT = UPDATE_JWT;
var LOGOUT = '@@resolve/LOGOUT'; //

exports.LOGOUT = LOGOUT;
var AUTH_REQUEST = '@@resolve/AUTH_REQUEST';
exports.AUTH_REQUEST = AUTH_REQUEST;
var AUTH_SUCCESS = '@@resolve/AUTH_SUCCESS';
exports.AUTH_SUCCESS = AUTH_SUCCESS;
var AUTH_FAILURE = '@@resolve/AUTH_FAILURE';
exports.AUTH_FAILURE = AUTH_FAILURE;
//# sourceMappingURL=action_types.js.map