export var SEND_COMMAND_REQUEST = '@@resolve/SEND_COMMAND_REQUEST';
export var SEND_COMMAND_SUCCESS = '@@resolve/SEND_COMMAND_SUCCESS';
export var SEND_COMMAND_FAILURE = '@@resolve/SEND_COMMAND_FAILURE'; //

export var DISPATCH_TOPIC_MESSAGE = '@@resolve/DISPATCH_TOPIC_MESSAGE'; //

export var SUBSCRIBE_TOPIC_REQUEST = '@@resolve/SUBSCRIBE_TOPIC_REQUEST';
export var SUBSCRIBE_TOPIC_SUCCESS = '@@resolve/SUBSCRIBE_TOPIC_SUCCESS';
export var SUBSCRIBE_TOPIC_FAILURE = '@@resolve/SUBSCRIBE_TOPIC_FAILURE';
export var UNSUBSCRIBE_TOPIC_REQUEST = '@@resolve/UNSUBSCRIBE_TOPIC_REQUEST';
export var UNSUBSCRIBE_TOPIC_SUCCESS = '@@resolve/UNSUBSCRIBE_TOPIC_SUCCESS';
export var UNSUBSCRIBE_TOPIC_FAILURE = '@@resolve/UNSUBSCRIBE_TOPIC_FAILURE'; //

export var CONNECT_VIEWMODEL = '@@resolve/CONNECT_VIEWMODEL';
export var DISCONNECT_VIEWMODEL = '@@resolve/DISCONNECT_VIEWMODEL';
export var LOAD_VIEWMODEL_STATE_REQUEST = '@@resolve/LOAD_VIEWMODEL_STATE_REQUEST';
export var LOAD_VIEWMODEL_STATE_SUCCESS = '@@resolve/LOAD_VIEWMODEL_STATE_SUCCESS';
export var LOAD_VIEWMODEL_STATE_FAILURE = '@@resolve/LOAD_VIEWMODEL_STATE_FAILURE';
export var DROP_VIEWMODEL_STATE = '@@resolve/DROP_VIEWMODEL_STATE'; //

export var CONNECT_READMODEL = '@@resolve/CONNECT_READMODEL';
export var DISCONNECT_READMODEL = '@@resolve/DISCONNECT_READMODEL';
export var LOAD_READMODEL_STATE_REQUEST = '@@resolve/LOAD_READMODEL_STATE_REQUEST';
export var LOAD_READMODEL_STATE_SUCCESS = '@@resolve/LOAD_READMODEL_STATE_SUCCESS';
export var LOAD_READMODEL_STATE_FAILURE = '@@resolve/LOAD_READMODEL_STATE_FAILURE';
export var DROP_READMODEL_STATE = '@@resolve/DROP_READMODEL_STATE'; //

export var HOT_MODULE_REPLACEMENT = '@@resolve/HOT_MODULE_REPLACEMENT'; //

export var UPDATE_JWT = '@@resolve/UPDATE_JWT';
export var LOGOUT = '@@resolve/LOGOUT'; //

export var AUTH_REQUEST = '@@resolve/AUTH_REQUEST';
export var AUTH_SUCCESS = '@@resolve/AUTH_SUCCESS';
export var AUTH_FAILURE = '@@resolve/AUTH_FAILURE';
//# sourceMappingURL=action_types.js.map